name: googleandfacebook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_facebook_auth: ^3.3.3+1
  firebase_auth: ^1.1.3
  google_sign_in: ^5.0.2
  firebase_core: ^1.1.1
  shared_preferences: ^2.0.5
  http: ^0.13.3
  share: ^2.0.1
  select_form_field: ^2.0.0
  shimmer: ^2.0.0
  hexcolor: ^2.0.4
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  file_picker: ^3.0.4
  google_maps_flutter: ^2.0.6
  geocoder: ^0.2.1
  geolocator: ^7.4.0
  image_picker: ^0.8.3+1
  logger: ^1.0.0
  otp_text_field: ^1.1.1
  auto_size_text: ^2.1.0
  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  url_launcher: ^6.0.9
  flutter_datetime_picker: ^1.5.1
  cloud_firestore: ^2.4.0
  photo_view: ^0.12.0
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^5.0.0+4
  fluttertoast: ^8.0.8
  firebase_storage: ^10.0.1
  firebase_storage_platform_interface: ^4.0.0
  table_calendar: ^3.0.2
  mime_type: ^1.0.0
  provider: ^6.0.0
  date_time_picker: ^2.1.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Login Page Folder/Images/google.jpeg
    - assets/Login Page Folder/Images/facebook.jpeg
    - assets/Login Page Folder/Images/background_image.png
    - assets/STAY CONNECTED PAGE/Welcome.png
    - assets/STAY CONNECTED PAGE/Stayconnected.png
    - assets/GetStarted/frontscreen.jpg 
    - assets/HomeScreen_images/blood-donation.png
    - assets/HomeScreen_images/calender.png
    - assets/HomeScreen_images/call.png
    - assets/HomeScreen_images/car.png
    - assets/HomeScreen_images/cooking.png
    - assets/HomeScreen_images/healthcare.png
    - assets/HomeScreen_images/image-gallery.png
    - assets/HomeScreen_images/job.png
    - assets/HomeScreen_images/matrimony.png
    - assets/HomeScreen_images/party.png
    - assets/HomeScreen_images/backgroundimages/bottombackground.png
    - assets/HomeScreen_images/backgroundimages/happy-family.webp
    - assets/Drawer/homeicon.png
    - assets/Drawer/message.png
    - assets/Drawer/treee.png
    - assets/Drawer/mapicon.png
    - assets/Drawer/accounticon.png
    - assets/Drawer/logoutt.png
    - assets/TreePageImages/PersonalDetails/profile.png
    - assets/TreePageImages/PersonalDetails/blood-type.png
    - assets/TreePageImages/PersonalDetails/cake.png
    - assets/TreePageImages/PersonalDetails/camera.svg
    - assets/TreePageImages/PersonalDetails/Community.png
    - assets/TreePageImages/PersonalDetails/female.svg
    - assets/TreePageImages/PersonalDetails/male.svg
    - assets/TreePageImages/PersonalDetails/religion.png
    - assets/TreePageImages/ContactDetails/smartphone.png
    - assets/TreePageImages/ContactDetails/whatsapp.png
    - assets/TreePageImages/ContactDetails/email.png
    - assets/TreePageImages/ContactDetails/house.png
    - assets/TreePageImages/ContactDetails/street-sign.png
    - assets/TreePageImages/ContactDetails/empire-state.png
    - assets/TreePageImages/ContactDetails/world.png
    - assets/TreePageImages/ContactDetails/city.jpeg
    - assets/TreePageImages/ProfessionalDetails/course.png
    - assets/TreePageImages/ProfessionalDetails/school.png
    - assets/TreePageImages/ProfessionalDetails/portfolio.png
    - assets/TreePageImages/ProfessionalDetails/office-building.png
    - assets/TreePageImages/ProfessionalDetails/location.png
    - assets/TreePageImages/ProfessionalDetails/cerficate.png
    - assets/TreePageImages/Tree/TreeAdd.jpeg
    - assets/TreePageImages/Tree/view.png
    - assets/TreePageImages/Tree/user.png
    - assets/TreePageImages/Tree/pencil.png
    - assets/TreePageImages/Tree/delete.png
    - assets/TreePageImages/Tree/sisters.png
    - assets/TreePageImages/Tree/mother.png
    - assets/TreePageImages/Tree/father.png
    - assets/TreePageImages/Tree/brothers.jpeg
    - assets/Matrimony/matrimonynew.jpeg
    - assets/Matrimony/matrimonybottom.jpg
    - assets/EVENTS ALL PAGE/imageCake.png
    - assets/EVENTS ALL PAGE/imageChild.png
    - assets/EVENTS ALL PAGE/imageGirl.png
    - assets/FamilyTourPlan/TourFirstTop.jpg
    - assets/FamilyTourPlan/TourFirstBottom.png
    - assets/FamilyTourPlan/add.png
    - assets/Try/shivangi.jpg
    - assets/JOBPORTAL/Joblaptop.jpg
    - assets/JOBPORTAL/Jobsearch.jpg
    - assets/JOBPORTAL/profile.jpg
    - assets/EVENTS ALL PAGE/birthday function.png
    - assets/FamilyTourPlan/tourplace.png
    - assets/FORGOTPASSWORD/changepassword.png
    - assets/FORGOTPASSWORD/forgotpassword.png
    - assets/FORGOTPASSWORD/verification.jpg
    - assets/HealthTips/HealthTipsFirst.png
    - assets/HealthTips/PostHealthTips/posthealthtips.png
    - assets/HealthTips/PostHealthTips/exercise.png
    - assets/HealthTips/PostHealthTips/childcare.png
    - assets/HealthTips/PostHealthTips/post.png
    - assets/HealthTips/download.jpg
    - assets/HealthTips/Image 30.png
    - assets/HealthTips/Image 31.png
    - assets/HealthTips/Image 32.png
    - assets/HealthTips/Image 33.png
    - assets/HealthTips/Image 34.png
    - assets/HealthTips/OIP.jpg
    - assets/Cooking Tips/cooking_tips_main_screen_image.png
    - assets/Cooking Tips/idli_image.png
    - images/img_not_available.jpeg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif
    - assets/Bloodmoduleimages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
